Add instruction for passing argument with leading dash
MicrosoftDocs/azure-docs-cli pull request #2318
Opened 2020-11-26 03:42 UTC by jiasli

Reported by https://github.com/Azure/azure-cli/issues/7054, https://github.com/Azure/azure-cli/issues/10692, https://github.com/Azure/azure-cli/issues/15493

Add instruction for passing argument with leading dash.

2020-11-26 03:43 UTC, opbld30 commented
Docs Build status updates of commit _[30b6135](https://github.com/jiasli/azure-docs-cli/commits/30b6135a4189c6a367a8b0d34afa03de0ae644cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/use-cli-effectively.md](https://github.com/jiasli/azure-docs-cli/blob/leading-dash/docs-ref-conceptual/use-cli-effectively.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/cli/azure/use-cli-effectively?branch=pr-en-us-2318) | [Details](#user-content-ac868391-5c632c1e)

<a id="ac868391-5c632c1e"></a>
### [docs-ref-conceptual/use-cli-effectively.md](https://github.com/jiasli/azure-docs-cli/blob/leading-dash/docs-ref-conceptual/use-cli-effectively.md)
 - **Line 121, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/overview?toc=./ref/toc.json&view=graph-rest-1.0`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/application?view=graph-rest-1.0`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-update?view=graph-rest-1.0&tabs=http`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202011260342173863-2318%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m4bDWadePFeQ%2BXHcCoHWLqq3xqqMCpAeebob012L9Pk%3D&st=2020-11-26T03%3A38%3A23Z&se=2020-12-27T03%3A43%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-26 06:08 UTC, qwordy approved these changes

2020-11-26 06:15 UTC, qwordy commented on docs-ref-conceptual/use-cli-effectively.md
> +2. If an argument's value contains special characters, like whitespace (` `) or quote (`"`, `'`), some quoting rules will apply. See below section:
"See below section" is a relative reference. I prefer deleting it.

2020-12-01 00:44 UTC, dbradish-microsoft requested changes

2020-12-01 00:44 UTC, dbradish-microsoft commented on docs-ref-conceptual/use-cli-effectively.md
> +1. If an argument's value starts with a dash (like `-VerySecret`), it will be parsed as an option (argument name, like `-n`) by [argparse](https://docs.python.org/3/library/argparse.html) (https://bu
@jiasli, please consider replacing "To force it to be parsed as value, use `--password="-VerySecret"`." with 
"
To force the value to be parsed correctly, place double quotes around it.  For example, `--password="-VerySecret"`.
"

2020-12-30 19:15 UTC, merged