1794885 using variables
MicrosoftDocs/azure-docs-cli pull request #2448
Opened 2021-02-22 18:54 UTC by TimShererWithAquent

This is for [1794885](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1794885) (part of [1774111](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1774111).

Builds aren't working currently. I'll check back after things are fixed.

2021-03-03 15:59 UTC, TimShererWithAquent commented
Close and reopen.

2021-03-03 15:59 UTC, TimShererWithAquent commented
Reopen.

2021-03-03 16:07 UTC, opbld32 commented
Docs Build status updates of commit _[7f0998c](https://github.com/TimShererWithAquent/azure-docs-cli/commits/7f0998c88a3f10aac92806c39c1238b5bd70223d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/azure-cli-variables.md](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/azure-cli-variables.md) | :x:Error | | [Details](#user-content-7cf71fd1-b3457147)

<a id="7cf71fd1-b3457147"></a>
### [docs-ref-conceptual/azure-cli-variables.md](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/azure-cli-variables.md)
 - **Line 23, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '/includes/azure-cli-prepare-your-environment.md'.`````
 - **Line 70, Column 105**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'manage-azure-subscriptions-azure-cli'.`````
 - **Line 86, Column 91**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/cli/azure/manage-azure-groups-azure-cli#set-a-default-resource-group' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202103031606226745-2448%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TiWIqgIsLsYVwjT22uM4T6Fdlk2CzxNarWV0xxLxEcQ%3D&st=2021-03-03T16%3A02%3A30Z&se=2021-04-03T16%3A07%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 17:19 UTC, opbld30 commented
Docs Build status updates of commit _[d597139](https://github.com/TimShererWithAquent/azure-docs-cli/commits/d59713986d63507434f2fe85ac5f12cb9d296e2c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-variables?branch=pr-en-us-2448) |
[docs-ref-conceptual/azure-cli-variables.md](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/azure-cli-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-variables?branch=pr-en-us-2448) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202103031709444366-2448%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v55RewtKZ9qAjGHMfX4huPsk26E3STgKVg5%2BVCRUSlI%3D&st=2021-03-03T17%3A14%3A45Z&se=2021-04-03T17%3A19%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 23:05 UTC, opbld30 commented
Docs Build status updates of commit _[c0eb373](https://github.com/TimShererWithAquent/azure-docs-cli/commits/c0eb373b57eb8502d73b02c1b3931ed4d819375d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-variables?branch=pr-en-us-2448) |
[docs-ref-conceptual/azure-cli-variables.md](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/azure-cli-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-variables?branch=pr-en-us-2448) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202103032304029167-2448%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HiMUHDp9H%2B2CJ71NL5Jz9Co3qNHomhsg0ZERkenrrSo%3D&st=2021-03-03T23%3A00%3A00Z&se=2021-04-03T23%3A05%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 20:00 UTC, dbradish-microsoft requested changes

2021-03-04 20:00 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-variables.md
> +## Set a subscription
@TimShererWithAquent , I'll need to come back to these additional H2s for later review.

2021-03-05 18:17 UTC, opbld33 commented
Docs Build status updates of commit _[b9a20ce](https://github.com/TimShererWithAquent/azure-docs-cli/commits/b9a20ce4ef468adb9d5c2ab02afc4617827951b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/TOC.yml](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-variables?branch=pr-en-us-2448) |
[docs-ref-conceptual/azure-cli-variables.md](https://github.com/TimShererWithAquent/azure-docs-cli/blob/us1774111f/docs-ref-conceptual/azure-cli-variables.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/azure-cli-variables?branch=pr-en-us-2448) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202103051816177585-2448%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FLzGtLn%2FXjVoyhBwCWrodOK0JcCyk88jkJk3kFsbunc%3D&st=2021-03-05T18%3A12%3A15Z&se=2021-04-05T18%3A17%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-08 18:04 UTC, merged