(Azure CXP) Doc Update
MicrosoftDocs/azure-docs-cli pull request #3063
Opened 2022-04-07 13:05 UTC by shashishailaj

updated line 143  from 

 az account list --query "[?isDefault == ``false``]"

to 

az account list --query "[?isDefault == `false`]"

As per MicrosoftDocs/azure-docs-cli/issues/3058

-------
cc: @dbradish-microsoft

2022-04-07 13:07 UTC, opbld31 commented
Docs Build status updates of commit _[84e4b44](https://github.com/shashishailaj/azure-docs-cli/commits/84e4b4438f9e16db9eb93669db63b5405a3373f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/query-azure-cli.md](https://github.com/shashishailaj/azure-docs-cli/blob/patch-1/docs-ref-conceptual/query-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/query-azure-cli?branch=pr-en-us-3063) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202204071305584834-3063%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T13%3A07%3A26Z&sr=b&sp=r&sig=sEBXw3l%2FJY0i0vnL2aNnjghOwvmYjge1xYuw1%2B%2BFCJQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-07 14:27 UTC, dbradish-microsoft requested changes

2022-04-07 14:27 UTC, dbradish-microsoft commented on docs-ref-conceptual/query-azure-cli.md
> +az account list --query "[?isDefault == ``false`]"
This is not correct.  There is an extra backtick in front of `false`.  Please change to -->

![image](https://user-images.githubusercontent.com/58762114/162222547-2681e595-88c5-42ef-9911-ad0e552c5b9a.png)

2022-04-07 14:54 UTC, opbld33 commented
Docs Build status updates of commit _[93a5f8e](https://github.com/shashishailaj/azure-docs-cli/commits/93a5f8e6ca3868679112b10b5a248ffbee9fbbad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-ref-conceptual/query-azure-cli.md](https://github.com/shashishailaj/azure-docs-cli/blob/patch-1/docs-ref-conceptual/query-azure-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/query-azure-cli?branch=pr-en-us-3063) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C7%5Cb11f9ddf-791c-c17b-454e-2902f9b37938%5CPullRequest%5C202204071453337618-3063%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-08T14%3A54%3A49Z&sr=b&sp=r&sig=71OY4%2F18pl3fgyU5H1ZCA0uDWTstjloycVmhQU%2F%2FrZU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-10 15:42 UTC, shashishailaj commented
@dbradish-microsoft Please review again when you can for sign-off . Thank you,

2022-04-21 13:25 UTC, dbradish-microsoft commented
I am closing this PR as this article has been rewritten and this line of code fixed.

2022-04-21 13:25 UTC, closed without merging