Updating the `az datafactory` documentation - not all functionality is available right now
MicrosoftDocs/azure-docs-cli pull request #3303
Opened 2022-09-12 14:21 UTC by mindlessroman

Hey folks -

Linking to https://github.com/Azure/azure-cli/issues/23844 - Updating the documentation to acknowledge that there is not 100% feature support on the AzCLI for all Data Factory components.

2022-09-12 14:24 UTC, opbld32 commented
Docs Build status updates of commit _[1bc3bcb](https://github.com/mindlessroman/azure-docs-cli/commits/1bc3bcb0edb98dfcfce193722c24aafcec764aa4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209121421466001-3303/BuildReport?accessString=37e645d9f51693f5d4803ca5964283845782bcd2333b97cbab0b112935699a55).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 15:28 UTC, chasewilson requested changes
Thanks for the PR! I just have a couple of comments and then we should be able to get this merged :)

2022-09-13 17:23 UTC, opbld31 commented
Docs Build status updates of commit _[e46fc35](https://github.com/mindlessroman/azure-docs-cli/commits/e46fc35fbee46589a0b0cfd801c322cd0264ae7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209131721460931-3303/BuildReport?accessString=285217db357125243cba51cd979e861bc867df97bdee08ac80f647e3e9878b8d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-13 17:26 UTC, mindlessroman commented on latest/docs-ref-autogen/datafactory.yml
> +  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, one can use the PowerShell module for [Data Factory.](https://docs.microsoft.com/en-us/powe
Good point on pointing out what's missing. It seems to be Data Flows primarily but it's worth confirming

As for a timeline, I'm not sure. I'm investigating how to add it, but I don't know how that will be prioritized in the next while.

2022-09-13 17:27 UTC, chasewilson commented on latest/docs-ref-autogen/datafactory.yml
> +  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, one can use the PowerShell module for [Data Factory.](https://docs.microsoft.com/en-us/powe
No worries about the timeline. If we don't have any info then it's better not to muddy the waters :) Thanks for the quick response and if we can get a little more guidance on what's missing, we'll get this merged in.

2022-09-13 21:53 UTC, mindlessroman commented on latest/docs-ref-autogen/datafactory.yml
> +  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, one can use the PowerShell module for [Data Factory.](https://docs.microsoft.com/en-us/powe
Sounds good! I'll try to firm up what's missing and update here!

2022-09-15 22:19 UTC, mindlessroman commented on latest/docs-ref-autogen/datafactory.yml
> +  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, one can use the PowerShell module for [Data Factory.](https://docs.microsoft.com/en-us/powe
Basing the findings by comparing what's available on https://docs.microsoft.com/en-us/powershell/module/az.datafactory/?view=azps-8.3.0#data-factories

2022-09-15 22:21 UTC, opbld31 commented
Docs Build status updates of commit _[fdc7fdf](https://github.com/mindlessroman/azure-docs-cli/commits/fdc7fdf0d7e80d5d8fdfcb23739bff7a240b4829)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) | [Details](#user-content-d6bacc4a51e24cf5acdd1948bb88de6d-d3edd106)

<a id="d6bacc4a51e24cf5acdd1948bb88de6d-d3edd106"></a>
### [latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml)
 - **Line 4, Column 23**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 8, Column 1**: **[Warning: invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209152219545068-3303/BuildReport?accessString=5e5b1d0a172face763370477a2455a9a564da0566dfc5cf114b449e57a78c403).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 16:38 UTC, opbld31 commented
Docs Build status updates of commit _[18ea3c7](https://github.com/mindlessroman/azure-docs-cli/commits/18ea3c7be7bd0d97c17af80b5014360b0c8cb4c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209161635596217-3303/BuildReport?accessString=c1d66d630e3e460945a3d0023ec0d55bd4e978bf5067ef985bb4512014506dbf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-16 18:38 UTC, mindlessroman commented on latest/docs-ref-autogen/datafactory.yml
> +
So it seems that this new line is necessary for the note formatting.

2022-09-19 16:47 UTC, chasewilson requested changes

2022-09-19 16:47 UTC, chasewilson commented on latest/docs-ref-autogen/datafactory.yml
> +  Gateways, Hubs; Saving Logs
```suggestion
  > Currently not supported: Data Flow commands; Activity Window; Data Factory Gateways, Hubs; Saving Logs.
  
```

2022-09-19 16:50 UTC, opbld30 commented
Docs Build status updates of commit _[f88c163](https://github.com/mindlessroman/azure-docs-cli/commits/f88c163eebe24ffd8712f2273bc3381c2b38fa8d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209191648195701-3303/BuildReport?accessString=673d65e3b216e1385c8ab11471c1b37de963b4ca1cc466115108ba3c798daa3d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 16:56 UTC, opbld32 commented
Docs Build status updates of commit _[7b3ba36](https://github.com/mindlessroman/azure-docs-cli/commits/7b3ba3679227b068b77fc2657953d181f742ca73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209191654534019-3303/BuildReport?accessString=47a7ef23ab04a29a4e32e55a395eec71684f0a9d1735748a4c3392d64f176e56).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-19 16:57 UTC, chasewilson approved these changes

2022-09-19 16:58 UTC, chasewilson commented on latest/docs-ref-autogen/datafactory.yml
> +  - Saving Logs
```suggestion
  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, please use the PowerShell module for [Data Factory](https://docs.microsoft.com/powershell/module/az.datafactory). Currently not supported: Data Flow commands, Activity Window, Data Factory Gateways, Hubs, Saving Logs
```

2022-09-19 17:00 UTC, opbld30 commented
Docs Build status updates of commit _[037b8f5](https://github.com/mindlessroman/azure-docs-cli/commits/037b8f5a215d8663accfa8a94a634957282fc362)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209191658572450-3303/BuildReport?accessString=eed811f4329889b5ce9c6189e9e69dd7b5ae0b309bdd3fe1616e1c642aec5e85).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 17:56 UTC, mindlessroman commented
@chasewilson - I don't have the ability to merge this, do you?

2022-09-20 18:19 UTC, chasewilson commented
Hey Hannah, I do :) I was just updating a few things for formatting and visual assistance but should have it merged by eod :)

2022-09-20 18:30 UTC, chasewilson commented on latest/docs-ref-autogen/datafactory.yml
> +  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, please use the PowerShell module for [Data Factory](https://docs.microsoft.com/powershell/m
```suggestion
  > Not all Data Factory functionality is supported in the CLI at this time. For any missing functionality, please use the PowerShell module for [Data Factory](https://docs.microsoft.com/powershell/module/az.datafactory). Currently not supported: **Data Flow commands**, **Activity Window**, **Data Factory Gateways**, **Hubs**, and **Saving Logs**
```

2022-09-20 18:34 UTC, opbld30 commented
Docs Build status updates of commit _[0841d11](https://github.com/mindlessroman/azure-docs-cli/commits/0841d11dbaec98c01517de03dfcfdd06eb93a678)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 19:24 UTC, chasewilson commented
Closed to kick of build

2022-09-20 19:26 UTC, opbld31 commented
Docs Build status updates of commit _[0841d11](https://github.com/mindlessroman/azure-docs-cli/commits/0841d11dbaec98c01517de03dfcfdd06eb93a678)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[latest/docs-ref-autogen/datafactory.yml](https://github.com/mindlessroman/azure-docs-cli/blob/mindlessroman/datafactory-data-flow-not-supported/latest/docs-ref-autogen/datafactory.yml) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/cli/azure/datafactory?view=azure-cli-latest&branch=pr-en-us-3303) (azure-cli-latest) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/b11f9ddf-791c-c17b-454e-2902f9b37938/202209201923572544-3303/BuildReport?accessString=bb85744f95681d08055f8e0a6695e31e586868d720553418a8435384fdc62f1e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b11f9ddf-791c-c17b-454e-2902f9b37938?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-20 19:27 UTC, merged

2022-09-20 19:28 UTC, chasewilson commented
A huge thank you @mindlessroman for this great update :)

2022-09-20 22:15 UTC, mindlessroman commented
Thank you, thank you @chasewilson !