added WAM information
MicrosoftDocs/azure-docs-cli pull request #3659
Opened 2023-05-19 21:24 UTC by dbradish-microsoft

This is a draft PR and will eventually mirror our Build 2023 announcement information/syntax.

2023-06-01 16:18 UTC, dcaro commented
@medhir can you review the verbiage on this WAM related content?

2023-06-01 23:07 UTC, medhir requested changes

2023-06-01 23:07 UTC, medhir commented on docs-ref-conceptual/authenticate-azure-cli.md
> +Signing in with WAM is a preview feature. Once turned on, it will replace the previous browser-based user interface.
```suggestion
Signing in with WAM is a preview, opt-in feature. Once enabled, it will replace the previous browser-based user interface. 
```

2023-06-01 23:07 UTC, medhir commented on docs-ref-conceptual/authenticate-azure-cli.md
> +_ Support for Windows Hello, conditional access, and FIDO keys.
```suggestion
_ Support for Windows Hello, conditional access policies, and FIDO keys.
```

2023-06-01 23:07 UTC, medhir commented on docs-ref-conceptual/authenticate-azure-cli.md
> +_ Fast single sign-on.
"Fast" seems too subjective. I'd make this more about the platform SSO benefits. 

```suggestion
_ Streamlined single sign-on.
```

2023-06-01 23:07 UTC, medhir commented on docs-ref-conceptual/authenticate-azure-cli.md
> +## Sign in with WAM
```suggestion
## Sign in with Web Account Manager (WAM)
```

2023-06-01 23:07 UTC, medhir commented on docs-ref-conceptual/authenticate-azure-cli.md
> +az config set core-allow_broker=true
```suggestion
az config set core.allow_broker=true
```

2023-06-06 20:18 UTC, dbradish-microsoft commented
@medhir , thank you for your suggested changes.  I've accepted each one and will merge this PR to Main.

2023-06-06 20:26 UTC, merged