Azure Service Principal for Azure CLI Rewrite
MicrosoftDocs/azure-docs-cli pull request #3798
Opened 2023-08-09 18:31 UTC by daphnemamsft

2023-08-11 13:55 UTC, dbradish-microsoft commented
@daphnemamsft , This PR looks like a WIP as I believe you are working to break this Tutorial down into multiple files, refresh and add possible content to each section (like output code blocks)?  I won't review until you are ready.

2023-09-21 19:18 UTC, dbradish-microsoft requested changes
A customer has to create a SP before they can "get" or "manage roles", so let's move 4 & 5 to be 2 & 3, and 2 & 3 down into the 4&5 slots.

Also please review https://review.learn.microsoft.com/en-us/help/patterns/level4/article-tutorial?branch=main and make sure we have followed Contributor guidelines.  Thank you!

2023-09-21 19:18 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-sp-tutorial-4.md
> +# 4 - Using Service Principal with password-based authentication
Let's change this to something like `Create a service principal using password-based authentication`.  Also, do a quick check that "service principal" isn't capitalized unless "Service" comes at the beginning of a sentence.

2023-09-21 19:18 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-sp-tutorial-5.md
> +# 5 - Using Service Principal with certificate-based authentication
Let's change this to something like `Create a service principal using certificate-based authentication`

2023-09-26 14:22 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-sp-tutorial-1.md
> +## Prerequisites
Prerequisites need to follow the azCLI [guidelines](https://review.learn.microsoft.com/en-us/help/contribute/conventions-azure-cli?branch=main#prerequisites).  Here is another example from inside this same repo: https://review.learn.microsoft.com/en-us/cli/azure/azure-cli-vm-tutorial-1?branch=pr-en-us-3798#prerequisites. It is also important to talk about the permissions needed in this prerequisite section.

Your markdown would look like this:

## Prerequisites
* To create a service principal, you must have ... <what permissions?>
[!INCLUDE [include](~/articles/reusable-content/azure-cli/azure-cli-prepare-your-environment-no-header.md)]

2023-09-28 18:14 UTC, merged

2024-11-07 05:41 UTC, jiasli commented on docs-ref-conceptual/azure-cli-sp-tutorial-3.md
> +For certificate-based authentication, use the `--cert` parameter. This parameter requires that you hold an existing certificate. Make sure any tool that uses this service principal has access to the
Why is `certificate` spelled as `certi897ficate`?

2024-11-07 05:50 UTC, jiasli commented on docs-ref-conceptual/azure-cli-sp-tutorial-3.md
> +> When using a PEM file, the **CERTIFICATE** must be appended to the **PRIVATE KEY** within the file.
This statement is wrong. The private key should not be passed: https://github.com/MicrosoftDocs/azure-docs-cli/issues/4734