Added PowerShell commands.
MicrosoftDocs/azure-docs-cli pull request #4124
Opened 2024-01-25 15:19 UTC by v-abdriaz

Added PowerShell commands and tabs.

2024-01-25 15:19 UTC, v-abdriaz commented
#sign-off

2024-01-25 19:24 UTC, dbradish-microsoft requested changes

2024-01-25 19:24 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-variables.md
> +$osType = (Get-AzVM -ResourceGroupName $MyResourceGroup -Name $vmName -SubscriptionName $MySubscription).StorageProfile.OsDisk.OsType
```suggestion
$osType=$(az vm get-instance-view --resource-group $MyResourceGroup `
   --name $vmName --subscription $MySubscription `
   --query 'storageProfile.osDisk.osType' --output tsv)
```

2024-01-25 19:24 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-variables.md
> +$osType = (Get-AzVM -ResourceGroupName $MyResourceGroup -Name $vmName -SubscriptionName $MySubscription).StorageProfile.OsDisk.OsType
@v-abdriaz , This is an Azure CLI article and ```azurecli code block that should only contain Azure CLI commands.

2024-01-25 19:24 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-variables.md
> +New-AzDisk -ResourceGroupName $MyResourceGroup -DiskName DestinationDisk -DiskSizeGB 20 -OsType $osType
```suggestion
az disk create --resource-group $MyResourceGroup --name DestinationDisk --size-gb 20 --os-type $osType
```

2024-01-25 19:24 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-variables.md
> +New-AzDisk -ResourceGroupName $MyResourceGroup -DiskName DestinationDisk -DiskSizeGB 20 -OsType $osType
@v-abdriaz , The point of this update is to show the customer how to run Azure CLI commands in a PowerShell environment. We should not be replacing Azure CLI commands with Azure PowerShell commands.  We need to make the Azure CLI command work.

2024-01-25 21:40 UTC, dbradish-microsoft commented on docs-ref-conceptual/azure-cli-variables.md
> +```azurecli
```suggestion
```azurecli-interactive
```

2024-01-30 01:26 UTC, dbradish-microsoft commented
@v-abdriaz , I'm a bit confused.  Where did the PowerShell conceptual tab go?  I gave you the syntax in one of the conversations.

2024-01-31 19:39 UTC, merged