release note for azure cli 2.67.0
MicrosoftDocs/azure-docs-cli pull request #4770
Opened 2024-11-13 07:48 UTC by azclibot

2024-11-13 07:52 UTC, jiasli approved these changes

2024-11-13 07:54 UTC, jiasli requested changes
Do not merge until 2024-11-19.

2024-11-19 02:34 UTC, jiasli commented on docs-ref-conceptual/release-notes-azure-cli.md
> +### DataLake
```suggestion
### Core

* PREVIEW: Support managed identity on Azure Arc-enabled Windows server

### DataLake
```

2024-11-19 02:37 UTC, jiasli commented on docs-ref-conceptual/release-notes-azure-cli.md
> +* `az container container-group-profile`: Add new command group to manage Azure Container Instance Container Group Profile(#30260)
```suggestion
* `az container container-group-profile`: Add new command group to manage Azure Container Instance Container Group Profile
```

2024-11-19 02:38 UTC, bebound approved these changes

2024-11-19 02:39 UTC, jiasli approved these changes

2024-11-19 02:41 UTC, jsntcy approved these changes

2024-11-19 02:41 UTC, merged